name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Retrieve code
        users: actions/checkout@v2

      - name: Say hello to the world
        run: echo "Hello, World!"
