name: Run hello_time script

on:
  push:
    branches:
      - main

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Retrieve code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run hello_with_timestamp.py
        run: |
          chmod +x hello_with_timestamp.py
          ./hello_with_timestamp.py > hello_timestamp_output.txt

      - name: Upload the output
        uses: actions/upload-artifact@v4
        with:
          name: hello_timestamp_output
          path: hello_timestamp_output.txt

